esphome:
  name: "${node_id}"
  platform: ESP8266
  board: esp8285

substitutions:
  node_id: "lanna-sw-02"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_id} Fallback Hotspot"
    password: !secret AP_pass
    
captive_portal:
#--------------------------#

binary_sensor:
  - platform: status
    name: "${node_id}"

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Tlačítko ${node_id}"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${node_id} rele"
    pin: GPIO12
    id: relay
  
status_led:
  pin:
    number: GPIO13
    inverted: yes


#--------------------------#
text_sensor:
  - platform: version
    name: "${node_id} version"
    hide_timestamp: True

button:
  - platform: restart
    name: "IOT ${node_id} RESTART"
  - platform: safe_mode
    name: "IOT ${node_id} Safe Mode"

logger:
ota:
  password: !secret ota_pass
api:
  password: !secret api_pass
  reboot_timeout: 15min
  encryption:
   key: !secret api_encrypt